# Generated by Django 6.0.7 on 2026-07-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_cliente', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id_freelancer', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='gestionCitas.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambos', 'Ambos')], default='ambos', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('id_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='gestionCitas.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='virtual', max_length=50)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='programada', max_length=30)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestionCitas.cliente')),
                ('id_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestionCitas.freelancer')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestionCitas.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='gestionCitas.freelancer')),
            ],
            options={
                'unique_together': {('id_freelancer', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='NoDisponibilidad',
            fields=[
                ('id_no_disponible', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('id_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_disponibilidades', to='gestionCitas.freelancer')),
            ],
            options={
                'unique_together': {('id_freelancer', 'fecha')},
            },
        ),
    ]
