# Generated by Django 6.0.7 on 2026-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contrasena',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='correo',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='virtual', max_length=15),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambos', 'Ambos')], default='ambos', max_length=12),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
