# Generated by Django 6.0.7 on 2026-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0002_alter_administrador_contrasena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo_cliente',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='categoria',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='contrasena',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='correo',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='modulo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='programada', max_length=12),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='virtual', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambos', 'Ambos')], default='ambos', max_length=10),
        ),
    ]
