# Generated by Django 6.0.7 on 2026-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0003_remove_freelancer_telefono_alter_cliente_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='categoria',
            field=models.CharField(choices=[('diseno_grafico', 'Diseño'), ('programacion', 'Programación'), ('musica', 'Música'), ('contabilidad', 'Contabilidad'), ('marketing_digital', 'Marketing Digital'), ('asesoria_legal', 'Asesoría Legal'), ('otro', 'Otra categoría')], default='otro', max_length=50),
        ),
    ]
