# Generated by Django 6.0.7 on 2026-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0004_alter_freelancer_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='categoria',
            field=models.CharField(choices=[('diseno_grafico', 'Diseño'), ('programacion', 'Programación'), ('musica', 'Música'), ('contabilidad', 'Contabilidad'), ('marketing_digital', 'Marketing Digital'), ('asesoria_legal', 'Asesoría Legal')], max_length=50),
        ),
    ]
