# Generated by Django 6.0.7 on 2026-07-31 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0005_alter_freelancer_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialcambio',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Historial de Cambio', 'verbose_name_plural': 'Historial de Cambios'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='activo',
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='datos_anteriores',
            field=models.JSONField(blank=True, help_text='Datos anteriores del registro', null=True),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='datos_nuevos',
            field=models.JSONField(blank=True, help_text='Datos nuevos del registro', null=True),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='registro_id',
            field=models.IntegerField(blank=True, help_text='ID del registro afectado', null=True),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='registro_nombre',
            field=models.CharField(blank=True, help_text='Nombre o descripción del registro afectado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Navegador del usuario', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('cancelar', 'Cancelar'), ('atender', 'Atender'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('reprogramar', 'Reprogramar'), ('confirmar', 'Confirmar'), ('rechazar', 'Rechazar'), ('activar', 'Activar'), ('desactivar', 'Desactivar'), ('exportar', 'Exportar'), ('importar', 'Importar'), ('resetear', 'Resetear')], db_index=True, help_text='Tipo de acción realizada', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to='gestionCitas.administrador'),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada de la acción realizada', max_length=500),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora del cambio'),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='modulo',
            field=models.CharField(choices=[('Sistema', 'Sistema'), ('Citas', 'Citas'), ('Servicios', 'Servicios'), ('Freelancers', 'Freelancers'), ('Clientes', 'Clientes'), ('Administradores', 'Administradores'), ('Usuarios', 'Usuarios'), ('Reportes', 'Reportes'), ('Disponibilidad', 'Disponibilidad'), ('Pagos', 'Pagos'), ('Notificaciones', 'Notificaciones'), ('Perfil', 'Perfil'), ('Seguridad', 'Seguridad')], db_index=True, help_text='Módulo del sistema afectado', max_length=50),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['fecha_hora'], name='gestionCita_fecha_h_2f16e2_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['accion', 'modulo'], name='gestionCita_accion_198394_idx'),
        ),
    ]
