# Generated by Django 6.0.7 on 2026-08-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCitas', '0006_alter_historialcambio_options_remove_cliente_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='calendar_event_url',
            field=models.URLField(blank=True, help_text='Enlace al evento en Google Calendar', max_length=500, null=True),
        ),
    ]
